import { Extension, textInputRule } from '@tiptap/core'

export const SmilieReplacer = Extension.create({
  name: 'smilieReplacer',

  addInputRules() {
    return [
      textInputRule({ find: /-___- $/, replace: '😑 ' }),
      textInputRule({ find: /:'-\) $/, replace: '😂 ' }),
      textInputRule({ find: /':-\) $/, replace: '😅 ' }),
      textInputRule({ find: /':-D $/, replace: '😅 ' }),
      textInputRule({ find: />:-\) $/, replace: '😆 ' }),
      textInputRule({ find: /-__- $/, replace: '😑 ' }),
      textInputRule({ find: /':-\( $/, replace: '😓 ' }),
      textInputRule({ find: /:'-\( $/, replace: '😢 ' }),
      textInputRule({ find: />:-\( $/, replace: '😠 ' }),
      textInputRule({ find: /:'\) $/, replace: '😂 ' }),
      textInputRule({ find: /:-D $/, replace: '😃 ' }),
      textInputRule({ find: /':\) $/, replace: '😅 ' }),
      textInputRule({ find: /'=\) $/, replace: '😅 ' }),
      textInputRule({ find: /':D $/, replace: '😅 ' }),
      textInputRule({ find: /'=D $/, replace: '😅 ' }),
      textInputRule({ find: />:\) $/, replace: '😆 ' }),
      textInputRule({ find: />;\) $/, replace: '😆 ' }),
      textInputRule({ find: />=\) $/, replace: '😆 ' }),
      textInputRule({ find: /;-\) $/, replace: '😉 ' }),
      textInputRule({ find: /\*-\) $/, replace: '😉 ' }),
      textInputRule({ find: /;-\] $/, replace: '😉 ' }),
      textInputRule({ find: /;\^\) $/, replace: '😉 ' }),
      textInputRule({ find: /B-\) $/, replace: '😎 ' }),
      textInputRule({ find: /8-\) $/, replace: '😎 ' }),
      textInputRule({ find: /B-D $/, replace: '😎 ' }),
      textInputRule({ find: /8-D $/, replace: '😎 ' }),
      textInputRule({ find: /:-\* $/, replace: '😘 ' }),
      textInputRule({ find: /:\^\* $/, replace: '😘 ' }),
      textInputRule({ find: /:-\) $/, replace: '🙂 ' }),
      textInputRule({ find: /-_- $/, replace: '😑 ' }),
      textInputRule({ find: /:-X $/, replace: '😶 ' }),
      textInputRule({ find: /:-# $/, replace: '😶 ' }),
      textInputRule({ find: /:-x $/, replace: '😶 ' }),
      textInputRule({ find: />.< $/, replace: '😣 ' }),

      textInputRule({ find: /:-O $/, replace: '😮 ' }),
      textInputRule({ find: /:-o $/, replace: '😮 ' }),
      textInputRule({ find: /:-0 $/, replace: '😮 ' }),
      textInputRule({ find: />:O $/, replace: '😮 ' }),
      textInputRule({ find: />:0 $/, replace: '😮 ' }),
      textInputRule({ find: />:o $/, replace: '😮 ' }),
      textInputRule({ find: /:0 $/, replace: '😮 ' }),
      textInputRule({ find: /:O $/, replace: '😮 ' }),
      textInputRule({ find: /:o $/, replace: '😮 ' }),

      textInputRule({ find: /0:3 $/, replace: '😇 ' }),
      textInputRule({ find: /0:\) $/, replace: '😇 ' }),
      textInputRule({ find: /0=\) $/, replace: '😇 ' }),
      textInputRule({ find: /O:\) $/, replace: '😇 ' }),
      textInputRule({ find: /O=\) $/, replace: '😇 ' }),
      textInputRule({ find: /O:3 $/, replace: '😇 ' }),
      textInputRule({ find: /o:\) $/, replace: '😇 ' }),
      textInputRule({ find: /o=\) $/, replace: '😇 ' }),
      textInputRule({ find: /o:3 $/, replace: '😇 ' }),
      textInputRule({ find: /O:-\) $/, replace: '😇 ' }),
      textInputRule({ find: /o:-\) $/, replace: '😇 ' }),
      textInputRule({ find: /0:-3 $/, replace: '😇 ' }),
      textInputRule({ find: /0:-\) $/, replace: '😇 ' }),
      textInputRule({ find: /0;\^\) $/, replace: '😇 ' }),
      textInputRule({ find: /O;-\) $/, replace: '😇 ' }),
      textInputRule({ find: /o;-\) $/, replace: '😇 ' }),
      textInputRule({ find: /0;-\) $/, replace: '😇 ' }),
      textInputRule({ find: /O:-3 $/, replace: '😇 ' }),
      textInputRule({ find: /o:-3 $/, replace: '😇 ' }),

      textInputRule({ find: /:-P $/, replace: '😛 ' }),
      textInputRule({ find: /:-p $/, replace: '😛 ' }),
      textInputRule({ find: /:-Þ $/, replace: '😛 ' }),
      textInputRule({ find: /:-þ $/, replace: '😛 ' }),
      textInputRule({ find: /:-b $/, replace: '😛 ' }),
      textInputRule({ find: />:P $/, replace: '😜 ' }),
      textInputRule({ find: /X-P $/, replace: '😜 ' }),
      textInputRule({ find: /x-p $/, replace: '😜 ' }),
      textInputRule({ find: /':\( $/, replace: '😓 ' }),
      textInputRule({ find: /'=\( $/, replace: '😓 ' }),
      textInputRule({ find: />:\\ $/, replace: '😕 ' }),
      textInputRule({ find: />:\/ $/, replace: '😕 ' }),
      textInputRule({ find: /:-\/ $/, replace: '😕 ' }),
      textInputRule({ find: /:-. $/, replace: '😕 ' }),
      textInputRule({ find: />:\[ $/, replace: '😞 ' }),
      textInputRule({ find: /:-\( $/, replace: '😞 ' }),
      textInputRule({ find: /:-\[ $/, replace: '😞 ' }),
      textInputRule({ find: /:'\( $/, replace: '😢 ' }),
      textInputRule({ find: /;-\( $/, replace: '😢 ' }),
      textInputRule({ find: /#-\) $/, replace: '😵 ' }),
      textInputRule({ find: /%-\) $/, replace: '😵 ' }),
      textInputRule({ find: /X-\) $/, replace: '😵 ' }),
      textInputRule({ find: />:\( $/, replace: '😠 ' }),
      textInputRule({ find: /<\/3 $/, replace: '💔 ' }),
      textInputRule({ find: /:D $/, replace: '😃 ' }),
      textInputRule({ find: /=D $/, replace: '😃 ' }),
      textInputRule({ find: /;\) $/, replace: '😉 ' }),
      textInputRule({ find: /\*\) $/, replace: '😉 ' }),
      textInputRule({ find: /;\] $/, replace: '😉 ' }),
      textInputRule({ find: /;D $/, replace: '😉 ' }),
      textInputRule({ find: /B\) $/, replace: '😎 ' }),
      textInputRule({ find: /8\) $/, replace: '😎 ' }),
      textInputRule({ find: /:\* $/, replace: '😘 ' }),
      textInputRule({ find: /=\* $/, replace: '😘 ' }),
      textInputRule({ find: /:\) $/, replace: '🙂 ' }),
      textInputRule({ find: /=\] $/, replace: '🙂 ' }),
      textInputRule({ find: /=\) $/, replace: '🙂 ' }),
      textInputRule({ find: /:\] $/, replace: '🙂 ' }),
      textInputRule({ find: /:X $/, replace: '😶 ' }),
      textInputRule({ find: /:# $/, replace: '😶 ' }),
      textInputRule({ find: /=X $/, replace: '😶 ' }),
      textInputRule({ find: /=x $/, replace: '😶 ' }),
      textInputRule({ find: /:x $/, replace: '😶 ' }),
      textInputRule({ find: /=# $/, replace: '😶 ' }),
      textInputRule({ find: /:P $/, replace: '😛 ' }),
      textInputRule({ find: /=P $/, replace: '😛 ' }),
      textInputRule({ find: /:p $/, replace: '😛 ' }),
      textInputRule({ find: /=p $/, replace: '😛 ' }),
      textInputRule({ find: /:Þ $/, replace: '😛 ' }),
      textInputRule({ find: /:þ $/, replace: '😛 ' }),
      textInputRule({ find: /:b $/, replace: '😛 ' }),
      textInputRule({ find: /d: $/, replace: '😛 ' }),
      textInputRule({ find: /:\/ $/, replace: '😕 ' }),
      textInputRule({ find: /:\\ $/, replace: '😕 ' }),
      textInputRule({ find: /=\/ $/, replace: '😕 ' }),
      textInputRule({ find: /=\\ $/, replace: '😕 ' }),
      textInputRule({ find: /:L $/, replace: '😕 ' }),
      textInputRule({ find: /=L $/, replace: '😕 ' }),
      textInputRule({ find: /:\( $/, replace: '😞 ' }),
      textInputRule({ find: /:\[ $/, replace: '😞 ' }),
      textInputRule({ find: /=\( $/, replace: '😞 ' }),
      textInputRule({ find: /;\( $/, replace: '😢 ' }),
      textInputRule({ find: /D: $/, replace: '😨 ' }),
      textInputRule({ find: /:\$ $/, replace: '😳 ' }),
      textInputRule({ find: /=\$ $/, replace: '😳 ' }),
      textInputRule({ find: /#\) $/, replace: '😵 ' }),
      textInputRule({ find: /%\) $/, replace: '😵 ' }),
      textInputRule({ find: /X\) $/, replace: '😵 ' }),
      textInputRule({ find: /:@ $/, replace: '😠 ' }),
      textInputRule({ find: /<3 $/, replace: '❤️ ' }),

      textInputRule({ find: /\/shrug $/, replace: '¯\\_(ツ)_/¯' }),
      textInputRule({ find: /\/lenny $/, replace: '( ͡° ͜ʖ ͡°)' }),
      textInputRule({ find: /\/tableflip $/, replace: '(╯°□°）╯︵ ┻━┻' }),
      textInputRule({ find: /\/unflip $/, replace: '┬─┬ ノ( ゜-゜ノ)' }),
      textInputRule({ find: /\/y $/, replace: '👍 ' }),
      textInputRule({ find: /\/n $/, replace: '👎 ' }),
      textInputRule({ find: /\/ok $/, replace: '👌 ' }),
      textInputRule({ find: /\/facepalm $/, replace: '🤦‍♂️ ' }),
      textInputRule({ find: /\/poop $/, replace: '💩 ' }),
      textInputRule({ find: /\/poopy $/, replace: '💩 ' }),
      textInputRule({ find: /\/shit $/, replace: '💩 ' }),
      textInputRule({ find: /\/clap $/, replace: '👏 ' }),
      textInputRule({ find: /\/pray $/, replace: '🙏 ' }),
      
      textInputRule({ find: /<--- $/, replace: '⟵ ' }),
      textInputRule({ find: /---> $/, replace: '⟶ ' }),
      textInputRule({ find: /<---> $/, replace: '⟷ ' }),

      textInputRule({ find: /===> $/, replace: '⟹ ' }),
      textInputRule({ find: /<=== $/, replace: '⟸ ' }),
      textInputRule({ find: /<===> $/, replace: '⟺ ' }),

      textInputRule({ find: /<-- $/, replace: '⟵ ' }),
      textInputRule({ find: /--> $/, replace: '⟶ ' }),
      textInputRule({ find: /<--> $/, replace: '⟷ ' }),

      textInputRule({ find: /==> $/, replace: '⟹ ' }),
      textInputRule({ find: /<== $/, replace: '⟸ ' }),
      textInputRule({ find: /<==> $/, replace: '⟺ ' }),

      textInputRule({ find: /-> $/, replace: '→ ' }), 
      textInputRule({ find: /<- $/, replace: '← ' }),
      textInputRule({ find: /<-> $/, replace: '↔ ' }),

      textInputRule({ find: /=> $/, replace: '⇒' }),
      textInputRule({ find: /<=> $/, replace: '⇔ ' }),
      textInputRule({ find: /!= $/, replace: '≠ ' }),
      textInputRule({ find: /=== $/, replace: '≡ ' }),
      textInputRule({ find: /!== $/, replace: '≢ ' }),
      textInputRule({ find: /<= $/, replace: '≤ ' }),
      textInputRule({ find: />= $/, replace: '≥ ' }),
      textInputRule({ find: /\.\.\. $/, replace: '… ' }),

      textInputRule({ find: /\/alpha $/, replace: 'α ' }),
      textInputRule({ find: /\/beta $/, replace: 'β ' }),
      textInputRule({ find: /\/gamma $/, replace: 'γ ' }),
      textInputRule({ find: /\/delta $/, replace: 'δ ' }),
      textInputRule({ find: /\/epsilon $/, replace: 'ε ' }),
      textInputRule({ find: /\/zeta $/, replace: 'ζ ' }),
      textInputRule({ find: /\/eta $/, replace: 'η ' }),
      textInputRule({ find: /\/theta $/, replace: 'θ ' }),
      textInputRule({ find: /\/iota $/, replace: 'ι ' }),
      textInputRule({ find: /\/kappa $/, replace: 'κ ' }),
      textInputRule({ find: /\/lambda $/, replace: 'λ ' }),
      textInputRule({ find: /\/mu $/, replace: 'μ ' }),
      textInputRule({ find: /\/nu $/, replace: 'ν ' }),
      textInputRule({ find: /\/xi $/, replace: 'ξ ' }),
      textInputRule({ find: /\/omicron $/, replace: 'ο ' }),
      textInputRule({ find: /\/pi $/, replace: 'π ' }),
      textInputRule({ find: /\/rho $/, replace: 'ρ ' }),
      textInputRule({ find: /\/sigma $/, replace: 'σ ' }),
      textInputRule({ find: /\/tau $/, replace: 'τ ' }),
      textInputRule({ find: /\/upsilon $/, replace: 'υ ' }),
      textInputRule({ find: /\/phi $/, replace: 'φ ' }),
      textInputRule({ find: /\/chi $/, replace: 'χ ' }),
      textInputRule({ find: /\/psi $/, replace: 'ψ ' }),
      textInputRule({ find: /\/omega $/, replace: 'ω ' }),

      textInputRule({ find: /\/Alpha $/, replace: 'Α ' }),
      textInputRule({ find: /\/Beta $/, replace: 'Β ' }),
      textInputRule({ find: /\/Gamma $/, replace: 'Γ ' }),
      textInputRule({ find: /\/Delta $/, replace: 'Δ ' }),
      textInputRule({ find: /\/Epsilon $/, replace: 'Ε ' }),
      textInputRule({ find: /\/Zeta $/, replace: 'Ζ ' }),
      textInputRule({ find: /\/Eta $/, replace: 'Η ' }),
      textInputRule({ find: /\/Theta $/, replace: 'Θ ' }),
      textInputRule({ find: /\/Iota $/, replace: 'Ι ' }),
      textInputRule({ find: /\/Kappa $/, replace: 'Κ ' }),
      textInputRule({ find: /\/Lambda $/, replace: 'Λ ' }),
      textInputRule({ find: /\/Mu $/, replace: 'Μ ' }),
      textInputRule({ find: /\/Nu $/, replace: 'Ν ' }),
      textInputRule({ find: /\/Xi $/, replace: 'Ξ ' }),
      textInputRule({ find: /\/Omicron $/, replace: 'Ο ' }),
      textInputRule({ find: /\/Pi $/, replace: 'Π ' }),
      textInputRule({ find: /\/Rho $/, replace: 'Ρ ' }),
      textInputRule({ find: /\/Sigma $/, replace: 'Σ ' }),
      textInputRule({ find: /\/Tau $/, replace: 'Τ ' }),
      textInputRule({ find: /\/Upsilon $/, replace: 'Υ ' }),
      textInputRule({ find: /\/Phi $/, replace: 'Φ ' }),
      textInputRule({ find: /\/Chi $/, replace: 'Χ ' }),
      textInputRule({ find: /\/Psi $/, replace: 'Ψ ' }),
      textInputRule({ find: /\/Omega $/, replace: 'Ω ' }),

      textInputRule({ find: /1\/2 $/, replace: '½ ' }),
      textInputRule({ find: /1\/3 $/, replace: '⅓ ' }),
      textInputRule({ find: /2\/3 $/, replace: '⅔ ' }),
      textInputRule({ find: /1\/4 $/, replace: '¼ ' }),
      textInputRule({ find: /3\/4 $/, replace: '¾ ' }),
      textInputRule({ find: /1\/5 $/, replace: '⅕ ' }),
      textInputRule({ find: /2\/5 $/, replace: '⅖ ' }),
      textInputRule({ find: /3\/5 $/, replace: '⅗ ' }),
      textInputRule({ find: /4\/5 $/, replace: '⅘ ' }),
      textInputRule({ find: /1\/6 $/, replace: '⅙ ' }),
      textInputRule({ find: /5\/6 $/, replace: '⅚ ' }),
      textInputRule({ find: /1\/7 $/, replace: '⅐ ' }),
      textInputRule({ find: /1\/8 $/, replace: '⅛ ' }),
      textInputRule({ find: /3\/8 $/, replace: '⅜ ' }),
      textInputRule({ find: /5\/8 $/, replace: '⅝ ' }),
      textInputRule({ find: /7\/8 $/, replace: '⅞ ' }),
      textInputRule({ find: /1\/9 $/, replace: '⅑ ' }),
      textInputRule({ find: /1\/10 $/, replace: '⅒ ' }),
    ]
  },
})